### ISSUE TITLE
Unable to retrieve semantic information from pdf  

### ISSUE THREAD

**Issue by onkar27** [datalogics/adobe-pdf-library-samples#14]
Semantic information means retrieving paragraphs under some heading/bookmark.

I'm currently trying to retrieve such information using 
`wordFinder.getWordList(pageNo);`  and getting all bookmarks.

Here words are in sequence so its easy to compare all words to fit inside viewDestination of respective bookmark and set it into that paragraph.

But it fails for positioning of Image because sequence of Image w.r.t. adjacent word is not there.

How do I fit Image under specific position in paragraph?

**Comment by datalogics-josepha** [comment]
Hello,

It's a bit difficult to understand what your goal is.  Have you opened an inquiry with our Support department yet (tech_support@datalogics.com)?

If not, please do so in order to more direct assistance.  An example of what you'd like to achieve and a sample PDF may be helpful when explaining this.

Thanks.

**Comment by datalogics-mdawson** [comment]
Issue sent to Support for review.
