### ISSUE TITLE
Feature Comparision

### ISSUE THREAD

**Issue by sarankup** [datalogics/adobe-pdf-library-samples#7]
Hi,

I want to start product development using PDF Library. I want to check with you whether any specific choice programming here (C++, .NET, JAVA) has much rich feature compare to other. If all are the same, then we can start with Java. If C++ is much superior in terms of feature, we can plan with C++.

Thanks in advance.

**Comment by datalogics-pgallot** [comment]
Hi,
The Java and .Net interfaces (which basically have feature parity between them) have some value-added features that are not available withAPDFL's C/C++ interface, but the C/C++ interface is what the Java and .Net interfaces are based on. Not all of APDFL's features are exposed in the Java and DotNet interfaces, but easily 90% of APDFL's functionality is exposed via the Java and .Net interfaces. 

All told, I would recommend starting with the Java interface, which is a bit easier to get started with versus the C/C++ interface.

**Comment by sarankup** [comment]
Hi,

We see the PDF Library SDK in both Adobe site and Datalogics.

Does both same? Or Datalogics is only having Java and .NET facilities?

**Comment by datalogics-pgallot** [comment]
Datalogics resells the Adobe PDF Library both as we receive it from Adobe and with our with our enhancements, add-ons, and fixes. The Java and .Net interfaces are add-ons from Datalogics.  In general, Adobe does not directly sell the PDF Library to customers. However, it does provide an Acrobat SDK which has a very similar interface to the PDF Library, with a bit more functionality than is provided by the PDF Library. The key difference is that the Acrobat SDK requires a copy of Acrobat Pro to run while the PDF Library can be used in a stand-alone application.

**Comment by coderabsolute** [comment]
Is it possible to view the C# documentation and the sample program before buying, with an assumption that C# and Java interface code is 100% same and their behavior?

**Comment by datalogics-pgallot** [comment]
@coderabsolute Just to clarify; APDFL has a Java and .Net interface that are generated from the same code base and while they are largely functionally identical, there are some minor aspects where they differ in order to better accommodate the VM-specific differences. Stream-IO comes to mind, for example.

The [evaluation package](https://www.datalogics.com/products/pdf/pdflibrary/eval/) does include documentation for both the DotNet and Java interfaces.

Also note that the Java interface is completely separate from our PDF Java Toolkit (PDFJT) which is pure Java from the ground up, and is not an interface to the C/C++ APDFL library.

[cid:image003.png@01D44F34.2491B6D0]Patrick Gallot
Application Support Engineer, Developer Support | Datalogics, Inc.
+1.312.853.8238 | pgallot@datalogics.com<mailto:jrp@datalogics.com>
 datalogics.com<http://www.datalogics.com/> | blogs.datalogics.com<http://blogs.datalogics.com/>

Connect with us: Facebook<https://www.facebook.com/DatalogicsInc> | Twitter<https://twitter.com/DatalogicsInc> | LinkedIn<https://www.linkedin.com/company/datalogics?actionToken=p%3Dp%253Dbiz-company-login%2526c%253D3217e65a-bdc2-4b38-8f9c-13c982e8c529%2526m%253Dcompany_feed%2526n%253D0%26t%3Da%253DisFolloweeOfPoster%25253Dfalse%252526distanceFromActor%25253D-1%252526actorType%25253D%252526likedByUser%25253Dfalse%252526targetId%25253D%252526recentCommentUrns%25253D%252526targetType%25253D%252526sponsoredFlag%25253DORGANIC%252526verbType%25253Dlinkedin%2525253Ashare%252526objectType%25253Dlinkedin%2525253Aarticle%252526totalShares%25253D0%252526activityId%25253Durn%2525253Ali%2525253Aactivity%2525253A6263731876121362433%252526recentLikerUrns%25253D%252526actorId%25253Durn%2525253Ali%2525253Acompany%2525253A14000%252526totalComments%25253D0%252526relevanceScore%25253D0%2E0%252526recentCommenterUrns%25253D%252526isPublic%25253Dtrue%252526time%25253D-1%252526totalLikes%25253D0%252526objectId%25253Durn%2525253Ali%2525253Aarticle%2525253A7793179909183391510%252526distanceFromNestedActor%25253D-1%2526s%253DORGANIC%2526u%253Durn%25253Ali%25253Aactivity%25253A6263731876121362433&atv=2> | YouTube<https://www.youtube.com/user/Datalogics>
